# golangci-lint configuration for jp-go-pgx-utils
# v2 configuration format
version: "2"

run:
  # Timeout for analysis - prevents CI hangs while allowing thorough checking
  timeout: 5m

formatters:
  enable:
    - gofmt
    - gofumpt       # Stricter formatting than gofmt
    - goimports

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - gosec

  settings:
    staticcheck:
      checks:
        - all
        - -ST1000  # Package comments - not enforced in this codebase
        - -ST1016  # Receiver names - legacy code has mixed names

    gosec:
      # Exclude specific rules that are problematic in test contexts
      excludes:
        - G306  # File permissions - test files create temporary files with standard 0o644 permissions

  exclusions:
    paths:
      - ".*\\.pb\\.go$"
      - ".*_gen\\.go$"
      - ".*_generated\\.go$"

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 10
